clear all; close all; clc;
load('I:\JBT_RERUN\DATASET\Rerun_CellPair_Data_Struct_with3cmBins_090617.mat')

%% output pattern (per row): [spike normalized xcorr central sum , rate map xcorr coefficient, behaviour (1=run, 2=rem, 3=nrem), region (1=mec, 2=ca1)]

output_table = [];  
for ii=1:211
    
    output_table = [output_table; ...
        cellRegion(1).cellPair(ii).state(1).midSum(1), cellRegion(1).cellPair(ii).state(1).rmCorrCoeffs, 1, 1; ...
        cellRegion(1).cellPair(ii).state(2).midSum(1), cellRegion(1).cellPair(ii).state(1).rmCorrCoeffs, 2, 1;...
        cellRegion(1).cellPair(ii).state(3).midSum(1), cellRegion(1).cellPair(ii).state(1).rmCorrCoeffs, 3, 1;...
        ];
end
for ii=1:78
    
    output_table = [output_table; ...
        cellRegion(2).cellPair(ii).state(1).midSum(1), cellRegion(2).cellPair(ii).state(1).rmCorrCoeffs, 1, 5; ...
        cellRegion(2).cellPair(ii).state(2).midSum(1), cellRegion(2).cellPair(ii).state(1).rmCorrCoeffs, 2, 5;...
        cellRegion(2).cellPair(ii).state(3).midSum(1), cellRegion(2).cellPair(ii).state(1).rmCorrCoeffs, 3, 5;...
        ];
end
save('F:\2017_09_08_Data_Table.dat','-ascii','-double','-tabs','output_table')